from pathlib import Path
import re


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    if old not in text:
        raise RuntimeError(f"anchor not found in {path}: {old[:120]!r}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


main_path = Path("main.py")
main_text = main_path.read_text(encoding="utf-8")
if "import os\n" not in main_text:
    if "import logging\n" in main_text:
        main_text = main_text.replace("import logging\n", "import logging\nimport os\n", 1)
    else:
        main_text = "import os\n" + main_text

helper = r'''
STRATEGY_FINGERPRINT_ENV = "MOMENTUM_STRATEGY_FINGERPRINT"
STRATEGY_STAMP_SOURCE_ENV = "MOMENTUM_STRATEGY_STAMP_SOURCE"


def attach_strategy_provenance(frame: pd.DataFrame) -> pd.DataFrame:
    """Attach the precomputed governed strategy fingerprint before persistence.

    The fingerprint is generated by strategy_governance.py before main.py runs.
    When the environment variable is absent (local or isolated smoke execution),
    the frame is returned unchanged apart from the defensive copy.
    """
    work = frame.copy()
    fingerprint = os.environ.get(STRATEGY_FINGERPRINT_ENV, "").strip()
    if work.empty or not fingerprint:
        return work
    source = os.environ.get(
        STRATEGY_STAMP_SOURCE_ENV, "DAILY_GOVERNED_WORKFLOW"
    ).strip() or "DAILY_GOVERNED_WORKFLOW"
    work["strategy_fingerprint"] = fingerprint
    work["strategy_app_version"] = APP_VERSION
    work["strategy_stamp_source"] = source
    return work


'''
if "def attach_strategy_provenance(" not in main_text:
    anchor = "def ranking_history_columns()"
    if anchor not in main_text:
        raise RuntimeError("ranking_history_columns anchor not found")
    main_text = main_text.replace(anchor, helper + anchor, 1)

pattern = re.compile(
    r'(?m)^(?P<indent>\s*)if state_update_allowed:\n(?P=indent)    write_ranking_history\(all_ranked, cfg\["data"\]\["ranking_history_path"\]\)'
)
if "all_ranked = attach_strategy_provenance(all_ranked)" not in main_text:
    main_text, count = pattern.subn(
        lambda match: (
            f'{match.group("indent")}all_ranked = attach_strategy_provenance(all_ranked)\n'
            f'{match.group("indent")}if state_update_allowed:\n'
            f'{match.group("indent")}    write_ranking_history(all_ranked, cfg["data"]["ranking_history_path"])'
        ),
        main_text,
        count=1,
    )
    if count != 1:
        raise RuntimeError("state update ranking write anchor not found")
main_path.write_text(main_text, encoding="utf-8")

# Replace stamp-live with an idempotent verifier that also checks the state snapshot.
evidence_path = Path("evidence_provenance.py")
evidence_text = evidence_path.read_text(encoding="utf-8")
new_stamp = r'''def stamp_live_ranking_history(
    ranking_path: str,
    report_path: str,
    fingerprint_path: str,
    audit_path: str,
    snapshot_root: str = "data/state_snapshots",
) -> dict[str, Any]:
    fingerprint_manifest = load_json(fingerprint_path)
    fingerprint = str(fingerprint_manifest.get("strategy_fingerprint", "")).strip()
    if not fingerprint:
        raise ValueError("strategy fingerprint is empty")
    current = current_strategy_fingerprint()
    if fingerprint != current:
        raise ValueError("strategy fingerprint snapshot does not match current code")

    report_date, state_update, app_version = report_state_update(report_path)

    def verify_or_stamp(path: Path, required: bool) -> dict[str, Any]:
        if not path.exists():
            if required:
                raise FileNotFoundError(str(path))
            return {
                "row_count": 0,
                "already_stamped": 0,
                "changed": False,
                "sha256": "",
            }
        frame = pd.read_csv(path, dtype={"code": str})
        if "date" not in frame.columns:
            raise ValueError(f"ranking state is missing date column: {path}")
        missing_columns = [
            column
            for column in (
                "strategy_fingerprint",
                "strategy_app_version",
                "strategy_stamp_source",
            )
            if column not in frame.columns
        ]
        for column in missing_columns:
            frame[column] = ""
        mask = frame["date"].astype(str) == report_date
        row_count = int(mask.sum())
        if required and row_count == 0:
            raise ValueError(f"no ranking rows found for report date {report_date}: {path}")
        existing = frame.loc[mask, "strategy_fingerprint"].fillna("").astype(str).str.strip()
        mismatch = existing.ne("") & existing.ne(fingerprint)
        if bool(mismatch.any()):
            raise ValueError(f"ranking rows already contain a different strategy fingerprint: {path}")
        already_stamped = int(existing.eq(fingerprint).sum())
        blank_rows = existing.eq("")
        changed = bool(missing_columns or blank_rows.any())
        if row_count:
            frame.loc[mask, "strategy_fingerprint"] = fingerprint
            frame.loc[mask, "strategy_app_version"] = app_version
            frame.loc[mask, "strategy_stamp_source"] = "DAILY_GOVERNED_WORKFLOW"
        if changed:
            atomic_write_csv(frame, path)
        return {
            "row_count": row_count,
            "already_stamped": already_stamped,
            "changed": changed,
            "sha256": sha256_file(path),
        }

    ranking_result = {
        "row_count": 0,
        "already_stamped": 0,
        "changed": False,
        "sha256": sha256_file(ranking_path),
    }
    snapshot_result = {
        "row_count": 0,
        "already_stamped": 0,
        "changed": False,
        "sha256": "",
    }
    snapshot_path = Path(snapshot_root) / report_date / "ranking_history.csv"
    if state_update:
        ranking_result = verify_or_stamp(Path(ranking_path), required=True)
        snapshot_result = verify_or_stamp(snapshot_path, required=True)
        if ranking_result["row_count"] != snapshot_result["row_count"]:
            raise ValueError("ranking history and state snapshot have different report-date row counts")

    audit = {
        "provenance_version": PROVENANCE_VERSION,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "ranking_path": ranking_path,
        "snapshot_path": str(snapshot_path),
        "report_date": report_date,
        "state_update_executed": state_update,
        "strategy_fingerprint": fingerprint,
        "strategy_app_version": app_version,
        "stamped_rows": ranking_result["row_count"],
        "already_stamped_rows": ranking_result["already_stamped"],
        "ranking_changed_by_verifier": ranking_result["changed"],
        "ranking_sha256": ranking_result["sha256"],
        "snapshot_verified": bool(state_update),
        "snapshot_stamped_rows": snapshot_result["row_count"],
        "snapshot_already_stamped_rows": snapshot_result["already_stamped"],
        "snapshot_changed_by_verifier": snapshot_result["changed"],
        "snapshot_sha256": snapshot_result["sha256"],
        "research_only": True,
    }
    atomic_write_json(audit, audit_path)
    return audit


'''
pattern = re.compile(
    r"def stamp_live_ranking_history\(.*?\n\ndef prepare_live_history\(",
    re.DOTALL,
)
match = pattern.search(evidence_text)
if not match:
    raise RuntimeError("stamp_live_ranking_history block not found")
evidence_text = evidence_text[: match.start()] + new_stamp + "def prepare_live_history(" + evidence_text[match.end() :]

evidence_text = evidence_text.replace(
    '    stamp.add_argument("--audit", default="output/evidence_stamp_audit.json")\n',
    '    stamp.add_argument("--audit", default="output/evidence_stamp_audit.json")\n'
    '    stamp.add_argument("--snapshot-root", default="data/state_snapshots")\n',
    1,
)
evidence_text = evidence_text.replace(
    '        result = stamp_live_ranking_history(args.ranking, args.report, args.fingerprint, args.audit)\n',
    '        result = stamp_live_ranking_history(\n'
    '            args.ranking, args.report, args.fingerprint, args.audit, args.snapshot_root\n'
    '        )\n',
    1,
)
evidence_path.write_text(evidence_text, encoding="utf-8")

# Generate the strategy fingerprint before main.py, export it to the process,
# and verify both ranking history and snapshot after report generation.
Path(".github/workflows/daily.yml").write_text(r'''name: Daily Momentum Report

on:
  schedule:
    # 16:45 JST = 07:45 UTC, Monday-Friday.
    - cron: '45 7 * * 1-5'
  workflow_dispatch:
    inputs:
      max_symbols:
        description: 'Verification only: limit scanned symbols. Use 0 for a full production run.'
        required: false
        default: '0'

permissions:
  contents: write

concurrency:
  group: daily-momentum-report-main
  cancel-in-progress: false

env:
  TZ: Asia/Tokyo
  PYTHONUNBUFFERED: '1'

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Check out main with history
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Snapshot governed strategy fingerprint before report
        id: strategy
        continue-on-error: true
        run: |
          python strategy_governance.py snapshot \
            --output data/strategy_fingerprint.json
          fingerprint=$(python - <<'PY'
          import json
          from pathlib import Path
          payload = json.loads(Path('data/strategy_fingerprint.json').read_text(encoding='utf-8'))
          print(payload['strategy_fingerprint'])
          PY
          )
          echo "MOMENTUM_STRATEGY_FINGERPRINT=${fingerprint}" >> "${GITHUB_ENV}"
          echo "MOMENTUM_STRATEGY_STAMP_SOURCE=DAILY_GOVERNED_WORKFLOW" >> "${GITHUB_ENV}"

      - name: Run report
        id: report
        if: steps.strategy.outcome == 'success'
        continue-on-error: true
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          MOMENTUM_MAX_SYMBOLS: ${{ inputs.max_symbols || '0' }}
        run: |
          mkdir -p output
          set -o pipefail
          python main.py 2>&1 | tee output/run.log

      - name: Write operational heartbeat
        id: heartbeat
        if: steps.report.outcome == 'success'
        continue-on-error: true
        env:
          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          python operations.py heartbeat \
            --report output/daily_report.xlsx \
            --output data/operations_heartbeat.json \
            --run-id "${GITHUB_RUN_ID}" \
            --run-url "${RUN_URL}" \
            --event-name "${GITHUB_EVENT_NAME}"

      - name: Verify ranking and snapshot strategy stamps
        id: evidence
        if: >-
          steps.strategy.outcome == 'success' &&
          steps.report.outcome == 'success' &&
          steps.heartbeat.outcome == 'success'
        continue-on-error: true
        run: |
          python evidence_provenance.py stamp-live \
            --ranking data/momentum_daily_ranking.csv \
            --report output/daily_report.xlsx \
            --fingerprint data/strategy_fingerprint.json \
            --audit output/evidence_stamp_audit.json \
            --snapshot-root data/state_snapshots

      - name: Validate state and apply bounded retention
        id: maintenance
        if: >-
          steps.strategy.outcome == 'success' &&
          steps.report.outcome == 'success' &&
          steps.heartbeat.outcome == 'success' &&
          steps.evidence.outcome == 'success'
        continue-on-error: true
        run: |
          python operations.py maintain \
            --heartbeat data/operations_heartbeat.json \
            --report output/state_maintenance.json \
            --snapshot-root data/state_snapshots \
            --daily-days 30 \
            --monthly-months 12

      - name: Persist complete production state
        id: persist
        continue-on-error: true
        if: >-
          steps.strategy.outcome == 'success' &&
          steps.report.outcome == 'success' &&
          steps.heartbeat.outcome == 'success' &&
          steps.evidence.outcome == 'success' &&
          steps.maintenance.outcome == 'success' &&
          (github.event_name == 'schedule' || inputs.max_symbols == '0' || inputs.max_symbols == '')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A -- \
            data/momentum_daily_ranking.csv \
            data/market_temperature.csv \
            data/sector_leader_signal_history.csv \
            data/paper_portfolio.csv \
            data/paper_trade_history.csv \
            data/paper_equity_history.csv \
            data/execution_audit.csv \
            data/operations_heartbeat.json \
            data/strategy_fingerprint.json \
            data/state_snapshots \
            data/jpx_list_cache.csv

          if git diff --cached --quiet; then
            echo "No production state changes to commit"
            exit 0
          fi

          git commit -m "Update complete daily momentum state"
          git fetch origin main
          git rebase origin/main

          for attempt in 1 2 3; do
            if git push origin HEAD:main; then
              exit 0
            fi
            echo "Push attempt ${attempt} failed"
            if [ "${attempt}" -lt 3 ]; then
              sleep $((attempt * 10))
              git fetch origin main
              git rebase origin/main
            fi
          done

          echo "Failed to persist production state after three attempts" >&2
          exit 1

      - name: Notify operational failure
        id: notify
        if: >-
          always() &&
          (steps.strategy.outcome == 'failure' ||
           steps.report.outcome == 'failure' ||
           steps.heartbeat.outcome == 'failure' ||
           steps.evidence.outcome == 'failure' ||
           steps.maintenance.outcome == 'failure' ||
           steps.persist.outcome == 'failure')
        continue-on-error: true
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          STRATEGY_OUTCOME: ${{ steps.strategy.outcome }}
          REPORT_OUTCOME: ${{ steps.report.outcome }}
          HEARTBEAT_OUTCOME: ${{ steps.heartbeat.outcome }}
          EVIDENCE_OUTCOME: ${{ steps.evidence.outcome }}
          MAINTENANCE_OUTCOME: ${{ steps.maintenance.outcome }}
          PERSIST_OUTCOME: ${{ steps.persist.outcome }}
        run: |
          stage="strategy-fingerprint"
          if [ "${STRATEGY_OUTCOME}" != "failure" ] && [ "${REPORT_OUTCOME}" = "failure" ]; then stage="report"; fi
          if [ "${STRATEGY_OUTCOME}" != "failure" ] && [ "${REPORT_OUTCOME}" != "failure" ] && [ "${HEARTBEAT_OUTCOME}" = "failure" ]; then stage="heartbeat"; fi
          if [ "${STRATEGY_OUTCOME}" != "failure" ] && [ "${REPORT_OUTCOME}" != "failure" ] && [ "${HEARTBEAT_OUTCOME}" != "failure" ] && [ "${EVIDENCE_OUTCOME}" = "failure" ]; then stage="evidence-stamp"; fi
          if [ "${STRATEGY_OUTCOME}" != "failure" ] && [ "${REPORT_OUTCOME}" != "failure" ] && [ "${HEARTBEAT_OUTCOME}" != "failure" ] && [ "${EVIDENCE_OUTCOME}" != "failure" ] && [ "${MAINTENANCE_OUTCOME}" = "failure" ]; then stage="state-maintenance"; fi
          if [ "${STRATEGY_OUTCOME}" != "failure" ] && [ "${REPORT_OUTCOME}" != "failure" ] && [ "${HEARTBEAT_OUTCOME}" != "failure" ] && [ "${EVIDENCE_OUTCOME}" != "failure" ] && [ "${MAINTENANCE_OUTCOME}" != "failure" ] && [ "${PERSIST_OUTCOME}" = "failure" ]; then stage="state-persistence"; fi
          python operations.py notify \
            --stage "${stage}" \
            --log output/run.log \
            --output output/ops_notification.txt \
            --run-id "${GITHUB_RUN_ID}" \
            --run-url "${RUN_URL}"

      - name: Upload report and operational diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: momentum-operations-${{ github.run_id }}
          retention-days: 90
          if-no-files-found: warn
          path: |
            output/daily_report.xlsx
            output/run.log
            output/state_maintenance.json
            output/evidence_stamp_audit.json
            output/ops_notification.txt
            data/operations_heartbeat.json
            data/strategy_fingerprint.json
            data/momentum_daily_ranking.csv
            data/market_temperature.csv
            data/sector_leader_signal_history.csv
            data/paper_portfolio.csv
            data/paper_trade_history.csv
            data/paper_equity_history.csv
            data/execution_audit.csv
            data/state_snapshots/**

      - name: Enforce operational success
        if: >-
          always() &&
          (steps.strategy.outcome == 'failure' ||
           steps.report.outcome == 'failure' ||
           steps.heartbeat.outcome == 'failure' ||
           steps.evidence.outcome == 'failure' ||
           steps.maintenance.outcome == 'failure' ||
           steps.persist.outcome == 'failure')
        run: |
          echo "Daily workflow failed an operational gate. Review the momentum-operations artifact." >&2
          exit 1
''', encoding="utf-8")

# Permanent CI includes atomic stamp tests.
ci_path = Path(".github/workflows/ci.yml")
ci = ci_path.read_text(encoding="utf-8")
if ".github/test_atomic_strategy_stamp.py" not in ci:
    ci = ci.replace(
        "          .github/test_capacity_analysis.py\n",
        "          .github/test_capacity_analysis.py .github/test_atomic_strategy_stamp.py\n",
        1,
    )
    new_step = '''      - name: Run atomic strategy stamp validation
        run: |
          set -o pipefail
          python .github/test_atomic_strategy_stamp.py 2>&1 | tee /tmp/atomic-strategy-stamp-test.log

'''
    anchor = "      - name: Run operational controls validation\n"
    if anchor not in ci:
        raise RuntimeError("CI operational controls anchor not found")
    ci = ci.replace(anchor, new_step + anchor, 1)
    ci = ci.replace(
        "            /tmp/capacity-analysis-test.log\n",
        "            /tmp/capacity-analysis-test.log\n            /tmp/atomic-strategy-stamp-test.log\n",
        1,
    )
ci_path.write_text(ci, encoding="utf-8")

validator_path = Path(".github/validate_workflows.py")
validator = validator_path.read_text(encoding="utf-8")
validator = validator.replace(
    '        "strategy_governance.py snapshot",\n',
    '        "Snapshot governed strategy fingerprint before report",\n'
    '        "MOMENTUM_STRATEGY_FINGERPRINT",\n'
    '        "MOMENTUM_STRATEGY_STAMP_SOURCE",\n'
    '        "strategy_governance.py snapshot",\n',
    1,
)
validator = validator.replace(
    '        "output/evidence_stamp_audit.json",\n',
    '        "output/evidence_stamp_audit.json",\n'
    '        "--snapshot-root data/state_snapshots",\n',
    1,
)
validator = validator.replace(
    '    main_source = (ROOT / "main.py").read_text(encoding="utf-8")\n',
    '    assert daily.index("Snapshot governed strategy fingerprint before report") < daily.index("Run report")\n\n'
    '    main_source = (ROOT / "main.py").read_text(encoding="utf-8")\n',
    1,
)
validator = validator.replace(
    '        "def evaluate_market_data_freshness(",\n',
    '        "def attach_strategy_provenance(",\n'
    '        "MOMENTUM_STRATEGY_FINGERPRINT",\n'
    '        "all_ranked = attach_strategy_provenance(all_ranked)",\n'
    '        "def evaluate_market_data_freshness(",\n',
    1,
)
validator_path.write_text(validator, encoding="utf-8")

print("atomic strategy stamping patch applied")
